"""update tables

Revision ID: 052ff4d543ef
Revises: 0c74df4c229d
Create Date: 2025-08-27 16:21:33.968977

"""
from typing import Sequence, Union

from pgvector.sqlalchemy import Vector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '052ff4d543ef'
down_revision: Union[str, None] = '0c74df4c229d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('violationss', sa.Column('embedding', Vector(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('violationss', 'embedding')
    # ### end Alembic commands ###
