"""Add tags to the table Violations

Revision ID: 0c74df4c229d
Revises: a69a1704acd2
Create Date: 2025-04-24 16:27:49.727411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c74df4c229d'
down_revision: Union[str, None] = 'a69a1704acd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('violationss', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('violationss', 'tags')
    # ### end Alembic commands ###
