"""remove upload_date table UploadedFile

Revision ID: 50e910f579c5
Revises: 86deaa0ac723
Create Date: 2025-01-27 10:58:32.759314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50e910f579c5'
down_revision: Union[str, None] = '86deaa0ac723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploadedfiles', 'upload_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploadedfiles', sa.Column('upload_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
