"""Initial revision

Revision ID: f3572504bb09
Revises: 
Create Date: 2024-11-27 16:36:03.203561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3572504bb09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    from sqlalchemy.dialects.postgresql import ENUM

    # Явное создание ENUM'ов с checkfirst=True
    department_enum = ENUM(
        'Management', 'Administrative', 'Accounting', 'Metrology', 'Passes', 'Dispatcher',
        'Medical', 'Commercial', 'Moscow', 'Mehanical', 'Power', 'IT', 'HR', 'Logistics',
        'Safety', 'OTK', 'Builders', 'Secrecy', 'Technical', 'Repair', 'Composition', 'Security',
        'Quality', 'Financial', 'Legal', 'Trade', 'Cafe', 'Transport', 'Power_suple', 'Workshop',
        'First_section', 'Precious_metals', 'Gold', 'Silver', 'Platinum', 'Rhodium', 'Recycling',
        'laboratory', 'Cleaning', 'General', 'outside',
        name='departments'
    )
    department_enum.create(op.get_bind(), checkfirst=True)

    violation_enum = ENUM(
        'Access_mode', 'Information_security', 'Work_schedule', 'Other',
        name='typeviolation'
    )
    violation_enum.create(op.get_bind(), checkfirst=True)

    # Теперь используем созданные enum'ы в колонках
    op.create_table('departmentusers',
        sa.Column('name', department_enum, nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('users',
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('address', sa.String(), nullable=False),
        sa.Column('phone_number', sa.String(), nullable=True),
        sa.Column('hired', sa.Date(), nullable=False),
        sa.Column('dismissal', sa.Date(), nullable=True),
        sa.Column('department_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['department_id'], ['departmentusers.id']),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('violationss',
        sa.Column('type_violation', violation_enum, nullable=True),
        sa.Column('date_violation', sa.DateTime(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )



    op.create_table('violationss',
    sa.Column('type_violation', sa.Enum('Access_mode', 'Information_security', 'Work_schedule', 'Other', name='typeviolation'), nullable=True),
    sa.Column('date_violation', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('violationss')
    op.drop_table('users')
    op.drop_table('departmentusers')
    # ### end Alembic commands ###
