"""Optional hiring field

Revision ID: 6790796eeb80
Revises: 831ed78ae80e
Create Date: 2025-01-21 10:38:45.577785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6790796eeb80'
down_revision: Union[str, None] = '831ed78ae80e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hired',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hired',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
